version: '3.8'
services:
  mkr-agent:
    image: ghcr.io/adrimtgn/mkr-agent:latest
    deploy:
      placement:
        constraints:
          - "node.role == worker"
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.chatui.rule=Host(`mkr-agent.local`)"
        - "traefik.http.routers.chatui.entrypoints=web"
        - "traefik.docker.network=swarm-internal"
        - "traefik.http.services.chatui.loadbalancer.server.port=9099"     
    environment:
      - MCP_URL=http://192.168.1.48:8000
      - OLLAMA_URL=http://ollama.local
      - MODEL=llama3.1
    networks:
      - swarm-internal

networks:
  swarm-internal:
    external: true